apiVersion: v1
kind: Service
metadata:
  name: song-recommender-frontend-service
  namespace: yuandong
spec:
  selector:
    app: yuandong-song-recommender-frontend
  ports:
  - port: 30502
    targetPort: 5000
    nodePort: 30502
    protocol: TCP
  type: NodePort 