apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ml-job-base.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- pvc.yaml

# We'll use overlays for different datasets instead of trying to use variables
# See the overlays/ds1 and overlays/ds2 directories for dataset-specific configurations

# To switch datasets, simply change the DATASET value below to either "ds1" or "ds2"
# and change the Job name suffix in the patch section to match

configMapGenerator:
- name: ml-training-config
  literals:
  - DATASET=ds1
  - MIN_SUPPORT=0.01
  - MIN_CONFIDENCE=0.01
  - MAX_PLAYLISTS=1000
  - MAX_SONGS_PER_PLAYLIST=1000

patches:
- patch: |-
    - op: replace
      path: /metadata/generateName
      value: song-recommender-ml-job-ds1-
  target:
    kind: Job
    generateName: song-recommender-ml-job-

# Adding a var reference for DATE to include current timestamp
vars:
- name: DATE
  objref:
    kind: ConfigMap
    name: ml-training-config
    apiVersion: v1
  fieldref:
    fieldpath: metadata.annotations.date
# This annotation will be added via command line when applying kustomize
# kubectl create -k . --kustomize-flag="configMapGenerator[0].annotations.date=$(date +%Y%m%d-%H%M%S)"

