apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ml-job-base.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- pvc.yaml


configMapGenerator:
- name: ml-training-config
  literals:
  - DATASET=ds1
  - MIN_SUPPORT=0.05
  - MIN_CONFIDENCE=0.1

vars:
- name: DATASET
  objref:
    kind: ConfigMap
    name: ml-training-config
    apiVersion: v1
  fieldref:
    fieldpath: data.DATASET
