apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ml-job-base.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- pvc.yaml

configMapGenerator:
- name: ml-training-config
  literals:
  - DATASET=ds1
  - MIN_SUPPORT=0.01
  - MIN_CONFIDENCE=0.01
  - MAX_PLAYLISTS=1000
  - MAX_SONGS_PER_PLAYLIST=1000