apiVersion: batch/v1
kind: Job
metadata:
  name: song-recommender-ml-job-ds1-no-five
  namespace: yuandong
spec:
  template:
    metadata:
      labels:
        app: yuandong-song-recommender-ml
    spec:
      initContainers:
      - name: copy-datasets
        image: busybox
        command: ["sh", "-c", "cp -r /home/yuandong/hw2/data/* /shared/data/"]
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
        - name: host-volume
          mountPath: /home/yuandong
      containers:
      - name: song-recommender-ml
        image: yuandongzhang/song-recommender-ml:1.0.5
        env:
        - name: DATA_DIR
          value: "/shared/data"
        - name: MIN_SUPPORT
          value: "0.05"
        - name: MIN_CONFIDENCE
          value: "0.1"
        command: ["python", "/app/train_model.py"]
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: song-recommender-pvc
      - name: host-volume
        hostPath:
          path: /home/yuandong
      restartPolicy: OnFailure
