apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-recommender-pvc
  namespace: yuandong
spec:
  selector:
    matchLabels:
      namespace: yuandong
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

      

